### ISSUE TITLE
Internship still displayed after list changes

### ISSUE THREAD

**Issue by gerhean** [AY1920S2-CS2103T-F10-2/main#141]
![Screenshot_21](https://user-images.githubusercontent.com/16630400/78246776-48d9f880-751c-11ea-9a7a-4471bf9e65ad.png)
I dunno if this is bug or intended 'feature'. Just gonna leave this here anyway.

**Comment by gerhean** [comment]
Also does not disappear if the internship is deleted

**Comment by foochifa** [comment]
I think the list change part should be okay to leave it be. But I will fix the internship deleted to remove the selection. Thanks for the catch!
