### ISSUE TITLE
Add photos to about us page

### ISSUE THREAD

**Issue by joanneong** [AY1920S2-CS2103T-F10-2/main#200]
Hi team, please make sure that everyone's photos have been added to the project. If it is done correctly, I should see photos on the about us page and the [tp showcase page](https://nus-cs2103-ay1920s2.github.io/website/admin/projectList.html)!

**Comment by wxwxwxwx9** [comment]
Hi Joanne! Gerhean and I placed the placeholder image given by the module website. 

Can I verify if it is still acceptable? 

![Screen Shot 2020-04-05 at 12 03 10 PM](https://user-images.githubusercontent.com/37920115/78466593-79e14580-7735-11ea-8371-d4885dc6d27e.png)

**Comment by joanneong** [comment]
Hi @wxwxwxwx9 ! Thanks for alerting me to this; I forgot about it :P In this case, yes, placeholder images are fine but can you make sure that you and Gerhean use different placeholder images?

**Comment by wxwxwxwx9** [comment]
Alright, will do! Sorry for the late reply and thanks for the update Joanne :-)

**Comment by gerhean** [comment]
Is any placeholder image ok?

**Comment by joanneong** [comment]
@gerhean I suppose so, but try to pick placeholder images that you won't mind being associated with!

**Comment by wxwxwxwx9** [comment]
All our photos are now unique!
