### ISSUE TITLE
Refactor Test Cases

### ISSUE THREAD

**Issue by foochifa** [AY1920S2-CS2103T-F10-2/main#40]
Refactor Test Cases to work with new Model and refactored Logic/Storage

**Comment by wxwxwxwx9** [comment]
**With reference to #54** 

I think we have our tests are covering a good amount currently (73.24%), with what @foochifa and @gerhean added for **Logic** and **Storage** test cases respectively. 

I think **Model** test cases are alright as well. 

However, following are the test cases that are not passing as of #54 :
- execute_multipleKeywords_multipleInternshipApplicationsFound() from **FindCommandTest**
- parseCommand_add() from **InternshipDiaryParserTest**
- parseCommand_edit() from **InternshipDiaryParserTest** 

I tried debugging to no avail at the moment. Will look into it in the near future. 

Also, we currently have a few test cases for **Tags** which are lying around currently. Maybe we can delete them? I left them in the codebase currently. 

Other than the above, I think the only thing that remains is adding more test cases to increase our coverage. I will continue working on this.
